name: deploy-infrastructure

on:
  push:
    branches:
      - main
    paths:
      - infra/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@main
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/main.bicep
        failOnStdErr: false
        scope: resourcegroup
        deploymentName: ${{ github.run_number}}
        region: canadacentral
        # parameters: './deploy/parameters/prod.parameters.json'